### ISSUE TITLE
Undefined index: timeInterval

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [thomasaull/CiTrigger#1]
`Notice: Undefined index: timeInterval in /dist/site/modules/CiTrigger/CiTrigger.module on line 15
`

**Comment by thomasaull** [comment]
@dsdsdsdsdsds hmm ist this an issue with a recent php version (>8) maybe?

**Comment by thomasaull** [comment]
Ah its a `Notice` not an error anyway. Shouldn‘t be an issue I think. Probably I could add an `isset` check beforehand

**Comment by dsdsdsdsdsds** [comment]
Yes, but the notice breaks the admin interface if config debug is true. And yes, `isset` is fixing the issue.

**Comment by thomasaull** [comment]
Should be fixed: https://github.com/thomasaull/CiTrigger/commit/d784416d2204f7bf15658fec4bdb802747da8930
